name: Build

on: 
  watch:
    types: started

jobs:
  build_linux:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libfcitx-qt5-dev
        sudo apt-get install tree
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.6.2

    - name: do debug
      run: |
        tree -L 2 /opt/
        tree -L 2 /usr/lib
        tree -L 2 /usr/lib/x86_64-linux-gnu
